# Arthmetic Operation

In [16]:
import numpy as np
var =np.array([1,2,3,4,5])
var_add=var+3
print(var_add)

[4 5 6 7 8]


In [18]:
var1 =np.array([1,2,3,4,5])
var_sub=var1-3
print(var_sub)

[-2 -1  0  1  2]


var2=np.array([1,2,3,4])
var3=np.array([1,2,3,4])
arr_add=np.add(var2,var3)

print(arr_add)

In [24]:
var4=np.array([1,2,3,4])
var5=np.array([5,2,4,8])
arr_sub=var4-var5

print(arr_sub)

[-4  0 -1 -4]


In [26]:
var=np.array([1,2,3,4,5])
arr_div=var/3

print(arr_div)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [32]:
var=np.array([1,2,3,4,5,6,7,8,9,10])
arr_mod=var%3

print(arr_mod)

[1 2 0 1 2 0 1 2 0 1]


# 2d array

In [57]:

var2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2d_add=np.add(var2d,4)

print(arr2d_add)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [59]:
var2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2d_sub=np.subtract(var2d,4)

print(arr2d_sub)

[[-3 -2 -1  0  1]
 [ 2  3  4  5  6]]


In [61]:
var2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2d_mul=np.multiply(var2d,4)

print(arr2d_mul)

[[ 4  8 12 16 20]
 [24 28 32 36 40]]


In [63]:
var2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2d_pow=np.power(var2d,4)
arr2d=var2d**4
print(arr2d)
print()
print(arr2d_pow)

[[    1    16    81   256   625]
 [ 1296  2401  4096  6561 10000]]

[[    1    16    81   256   625]
 [ 1296  2401  4096  6561 10000]]


In [65]:
var2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
var2D=np.array([[1,2,3,4,9],[5,6,7,8,1]])

arr2d_add=np.add(var2d,var2D)
print(arr2d_add)

[[ 2  4  6  8 14]
 [11 13 15 17 11]]
