# arthmetic opertaion basic

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(f"Max value: {np.min(arr)}")
print(f"Max Location: {np.argmin(arr)}")

Max value: 1
Max Location: 0


In [39]:
arr=np.array([1,2,3,4,5])
arr_max=np.max(arr)
print(f"Max value: {arr_max}")
print(f"Max Location: {np.argmax(arr)}")
print(f"sqrt :{np.sqrt(arr)}")

Max value: 5
Max Location: 4
sqrt :[1.         1.41421356 1.73205081 2.         2.23606798]


# axis=0 mean coloumn check hoga in 2d
# axis=1 mean row wise check hoga

In [35]:
arr2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f"min value axis 0: {np.min(arr2d,axis=0)}")
print(f"min value axis 1: {np.min(arr2d,axis=1)}")
print(f"min Location: {np.argmin(arr2d)}")

min value axis 0: [1 2 3 4 5]
min value axis 1: [1 6]
min Location: 0


In [37]:
arr2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(f"max value axis 0 : {np.max(arr2d,axis=0)}")
print(f"max value axis 1 : {np.max(arr2d,axis=1)}")
print(f"Max Location: {np.argmax(arr)}")

max value axis 0 : [ 6  7  8  9 10]
max value axis 1 : [ 5 10]
Max Location: 9


In [43]:
arr=np.array([1,2,3,4,5])
print(np.sin(arr))
print(np.cos(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [45]:
arr=np.array([1,2,3,4,5])
print(np.cumsum(arr))

[ 1  3  6 10 15]
