# BROADCASTING

In [38]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
print(arr1.shape)
print()
arr2=np.array([[1],[2],[3]])
print(arr2)
print(arr2.shape)
print()
print(f"The sum of array1 and array 2 is:")
print(np.add(arr1,arr2))

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

The sum of array1 and array 2 is:
[[2 3 4]
 [3 4 5]
 [4 5 6]]
