# copy vs view

In [20]:
import numpy as np

arr=np.array([1,2,3,4,5])
x=arr.copy()
print(arr)
print(x)
print()
arr[1]=40
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]

[ 1 40  3  4  5]
[1 2 3 4 5]


In [18]:
arr1=np.array([6,7,8,9,10])
y=arr1.view()
print(arr1)

print(y)
print()
arr1[2]=30
print(arr1)
print(y)

[ 6  7  8  9 10]
[ 6  7  8  9 10]

[ 6  7 30  9 10]
[ 6  7 30  9 10]
