Data Type

In [6]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(f"Data type : {arr.dtype}")

Data type : int32


In [8]:
arr=np.array([1.2,2.3,3.8,4.1,5.0])
print(f"Data type : {arr.dtype}")

Data type : float64


In [10]:
arr=np.array(["a","b","c","d","e"])
print(f"Data type : {arr.dtype}")


Data type : <U1


In [12]:
arr=np.array(["a","b","c","d","e",1,2,3,4])
print(f"Data type : {arr.dtype}")

Data type : <U11


In [16]:
x=np.array([1,2,3,4,5],dtype=np.int8)

print(f"Data Type: {x.dtype}")

Data Type: int8


In [32]:
x=np.array([1,2,3,4,5],dtype="S")

print(f"Data Type: {x.dtype}")

Data Type: |S1


In [44]:
x=np.array([1,2,3,4,5])
new=np.float32(x)
print(f"Data Type: {x.dtype}")
print(f"Data Type: {new.dtype}")
print(x)
print(new)



Data Type: int32
Data Type: float32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [42]:
x=np.array([1,2,3,4,5])
new=np.int_(new)
print(f"Data Type: {x.dtype}")
print(f"Data Type: {new.dtype}")

print(x)
print(new)

Data Type: int32
Data Type: int32
[1 2 3 4 5]
[1 2 3 4 5]
