# Indexing

In [18]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr[1])
print(arr[-3])
    

2
2


In [22]:
arr1=np.array([[1,2,3],[5,5,6]])
print(arr1[(0,1)])
print(arr1[(1,2)])

2
6


In [57]:
arr3=np.array([[[1,2,3,4],[5,6,7,8]],[[12,4,98,6],[5,3,34,9]]])
print(arr3)
print(arr3.shape)
print()

print(arr3[(1,1,0)])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[12  4 98  6]
  [ 5  3 34  9]]]
(2, 2, 4)

5


# slicing

In [70]:
var=np.array([1,2,3,4,5,6,7,8])
print(var)
print()

print(f"2 to 5 {var[1:5]}")
print(f"2 to end {var[1:]}")
print(f"Start to 5 {var[:5]}")
print(var[::2])
print(var[::-1])


[1 2 3 4 5 6 7 8]

2 to 5 [2 3 4 5]
2 to end [2 3 4 5 6 7 8]
Start to 5 [1 2 3 4 5]
[1 3 5 7]
[8 7 6 5 4 3 2 1]


In [86]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print()
print(arr2[0,1:])
print(f"7 to 10 :{arr2[1,1:]}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[2 3 4 5]
7 to 10 :[ 7  8  9 10]
