# Insert Function

In [7]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print()
i=np.insert(arr,2,10)
print(i)

[1 2 3 4 5]

[ 1  2 10  3  4  5]


In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
ins1=np.insert(arr,2,6,axis=1)
ins0=np.insert(arr,1,[22,33,44,55],axis=0)
print(ins1)
print()
print(ins0)


[[1 2 6 3 4]
 [5 6 6 7 8]]

[[ 1  2  3  4]
 [22 33 44 55]
 [ 5  6  7  8]]


# delete

In [11]:
arr=np.array([1,2,3,4,5])
de=np.delete(arr,1)
print(de)


[1 3 4 5]


In [21]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
de=np.delete(arr1,5)
print(de)

[1 2 3 4 5 7 8]
