# iterating

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print()

for i in arr:
    print(i,end=" ")

[1 2 3 4 5 6]

1 2 3 4 5 6 

In [30]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print()

for i in arr2:
    print(i)
print()

for k in arr2:
    for l in k:
        print(l,end=" ")
    print()

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1 2 3 4 
5 6 7 8 


In [40]:
arr3=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr3)
print()

for i in arr3:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()

[[[1 2 3 4]
  [5 6 7 8]]]

1 2 3 4 
5 6 7 8 


In [44]:
arr3=np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr3)
print()

for i,d in np.ndenumerate(arr3):
    print(i,d)

[[[1 2 3 4]
  [5 6 7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
