# Join Array

In [6]:
import numpy as np

arr=np.array([1,2,3,4])
arr1=np.array([5,2,7,8])
ar=np.concatenate((arr,arr1))
print(ar)

[1 2 3 4 5 2 7 8]


In [14]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[3,2,1],[6,5,4]])
print(arr1)
print()
print(arr2)
print()
arr_0=np.concatenate((arr1,arr2),axis=0)
arr_1=np.concatenate((arr1,arr2),axis=1)
print(arr_0)
print()
print(arr_1)

[[1 2 3]
 [4 5 6]]

[[3 2 1]
 [6 5 4]]

[[1 2 3]
 [4 5 6]
 [3 2 1]
 [6 5 4]]

[[1 2 3 3 2 1]
 [4 5 6 6 5 4]]


# stack

In [35]:
arr1=([1,2,3,4])
arr2=([5,6,7,8])
a_new0=np.stack((arr1,arr2),axis=0)# coloumn
a_new1=np.stack((arr1,arr2),axis=1) #row
a_new2=np.hstack((arr1,arr2)) #row
a_new3=np.vstack((arr1,arr2)) #coloumn
a_new4=np.dstack((arr1,arr2)) #height
print(f"{a_new0}")
print()
print(f"{a_new1}")
print()
print(f"{a_new2}")
print()
print(f"{a_new3}")
print()
print(f"{a_new4}")

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [21]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[3,2,1],[6,5,4]])

a_new0=np.stack((arr1,arr2),axis=0)
a_new1=np.stack((arr1,arr2),axis=1)
print(a_new0)
print()
print(a_new1)

[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [6 5 4]]]

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [6 5 4]]]
