# matrix

In [5]:
import numpy as np

mat1=np.matrix([[1,2],[4,5]])
mat2=np.matrix([[1,2],[4,5]])

print(mat1.dot(mat2))
print()
print(np.dot(mat1,mat2))
print()
print(mat1@mat2)


[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


# Matrix Function

In [28]:
mat=np.matrix([[1,2],[3,4],[5,6]])
print("Original Matrix\n",mat)
print()
print("Matrix After Transpose\n",np.transpose(mat))
print()
print(mat.T)
print()
print(np.swapaxes(mat,0,1))


Original Matrix
 [[1 2]
 [3 4]
 [5 6]]

Matrix After Transpose
 [[1 3 5]
 [2 4 6]]

[[1 3 5]
 [2 4 6]]

[[1 3 5]
 [2 4 6]]


In [40]:
mat=np.matrix([[1,2],[5,6]])
print("Original Matrix\n",mat)
print()
print("After Inverse of Matrix\n",np.linalg.inv(mat))


Original Matrix
 [[1 2]
 [5 6]]

After Inverse of Matrix
 [[-1.5   0.5 ]
 [ 1.25 -0.25]]


In [42]:
mat=np.matrix([[1,2],[5,6]])
print("Original Matrix\n",mat)
print()
print(np.dot(mat,mat))


Original Matrix
 [[1 2]
 [5 6]]

[[11 14]
 [35 46]]


In [52]:
mat=np.matrix([[1,2],[5,6]])
print("Original Matrix\n",mat)
print()
print(np.linalg.matrix_power(mat,2))
print()
print(np.linalg.matrix_power(mat,0))
print()
print(np.linalg.matrix_power(mat,-2))

Original Matrix
 [[1 2]
 [5 6]]

[[11 14]
 [35 46]]

[[1 0]
 [0 1]]

[[ 2.875  -0.875 ]
 [-2.1875  0.6875]]


In [62]:
mat=np.matrix([[1,2],[5,6]])

print(mat)
print()
print("Determinant of Matrix\n",np.linalg.det(mat))


[[1 2]
 [5 6]]

Determinant of Matrix
 -3.999999999999999
