Array

In [5]:
import numpy  as np

x=[1,2,3,4,5]
y=np.array(x)
print(y)
print(y.ndim)


[1 2 3 4 5]
1


In [7]:
l=[]

for i in range(1,5):
    num=int(input("Enter number : "))
    l.append(num)
print(np.array(l))



Enter number :  1
Enter number :  2
Enter number :  3
Enter number :  4


[1 2 3 4]


In [9]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])

print(arr2)
print(f"The dimension of the array is : {arr2.ndim}")


[[1 2 3 4]
 [5 6 7 8]]
The dimension of the array is : 2


In [11]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)
print(f"The dimension of the array is : {arr2.ndim}")



[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The dimension of the array is : 2


In [13]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(f"The dimension of the array is : {arn.ndim}")


[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
The dimension of the array is : 10
