In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr=np.random.rand(5)
print(arr)


[0.00434528 0.32171006 0.54292314 0.48096272 0.74389679]


In [16]:
arr =np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [22]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a)
print(b)
print()
print(a+b)
print()
print(a*b)
print()
print(a-b)
print()
print(a/b)

[10 20 30]
[1 2 3]

[11 22 33]

[10 40 90]

[ 9 18 27]

[10. 10. 10.]


In [64]:
arr = np.arange(1, 21).reshape(4, 5)
print(arr)
print()
print(arr[:2,:])
print()
print(arr[:,-1])
print()
print(arr[1:3,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 5 10 15 20]

[[ 7  8]
 [12 13]]


In [72]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr_new=arr[arr<=10]
print(arr_new)

[ 1  2  3  4  5  6  7  8  9 10]


In [86]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix multiplication\n",arr1@arr2)
print()
print(np.dot(arr1,arr2))
print()
print("Element wise multiplication\n",np.multiply(arr1,arr2))


Matrix multiplication
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Element wise multiplication
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [100]:
arr=np.random.randint(1,100,50)
print(arr)

print("Mean :",np.mean(arr))
print()
print("Median :",np.median(arr))
print()
print("standard deviation :",np.std(arr))

[88 32 97 41 24 88 17 48 31 17 74 71 69 70 35 21 45  8 86 37 51 30 34 18
 67 84 38 94 86 72 11 79 70 88 15 30 15 25 97 15 92 40 79 86 77 66 98 16
 81 84]
Mean : 54.74

Median : 58.5

standard deviation : 29.106569705137016


In [104]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print(arr)
print()
print("Unique element",np.unique(arr))

[1 2 2 3 4 4 5]

Unique element [1 2 3 4 5]


In [124]:
arr=np.array([1,2,3,42,135,145,11,2,9,13,55])
arr1=np.sort(arr)
arr2=np.sort(arr)[::-1]
print(arr1)
print()
print(arr2)

[  1   2   2   3   9  11  13  42  55 135 145]

[145 135  55  42  13  11   9   3   2   2   1]


In [132]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([1,2,3])

arr_new=arr1+arr2

print("Original Array \n",arr1)
print()
print("1D Array \n",arr2)
print()
print("Result after broadcasting\n",arr1+arr2)


Original Array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array 
 [1 2 3]

Result after broadcasting
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [140]:
arr = np.array([10, 20, 30, 40, 50])
arr_new=arr[1::+2]
print(arr_new)


[20 40]


In [204]:
arr=np.array([[1,2,3,5],[4,5,6,6],[6,7,8,9],[12,10,11,12]])
print(arr,"\n")

compute=0
j=0

for i in range(0,4):
    compute+=arr[i,j]
    j+=1
print("Digonal value",np.diagonal(arr))
print()
print("The compute of the diagonal: ",compute)

[[ 1  2  3  5]
 [ 4  5  6  6]
 [ 6  7  8  9]
 [12 10 11 12]] 

Digonal value [ 1  5  8 12]

The compute of the diagonal:  26


In [174]:
arr=np.eye(4)
print(arr)

arr_new=np.diagonal(arr)
print("diagonal Elemnet:",arr_new)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
diagonal Elemnet: [1. 1. 1. 1.]


In [226]:
arr=np.array([[1,2,3,5],[4,5,6,6],[6,7,8,9],[12,10,11,12]])
print(arr.reshape(-1))
print()
print(arr.reshape(4,4))
print()
print(arr.reshape(2,8))
print()
print(arr.reshape(8,2))

[ 1  2  3  5  4  5  6  6  6  7  8  9 12 10 11 12]

[[ 1  2  3  5]
 [ 4  5  6  6]
 [ 6  7  8  9]
 [12 10 11 12]]

[[ 1  2  3  5  4  5  6  6]
 [ 6  7  8  9 12 10 11 12]]

[[ 1  2]
 [ 3  5]
 [ 4  5]
 [ 6  6]
 [ 6  7]
 [ 8  9]
 [12 10]
 [11 12]]
