Random

Rand()

In [7]:
import numpy as np
var =np.random.rand(4)
print(var)

[0.72229745 0.97507955 0.89875024 0.27223189]


In [9]:
var1=np.random.rand(3,5)
print(var1)

[[0.5950538  0.94977212 0.80411775 0.06988033 0.95323832]
 [0.72102583 0.09134711 0.77468873 0.14090373 0.41840056]
 [0.42262335 0.5631763  0.24157029 0.11815854 0.74168035]]


Randn

In [11]:
var2=np.random.randn(5)
var3=np.random.randn(4,4)
print(var2)
print("2d Array")
print(var3)


[ 2.42079841 -1.68395979 -0.82349742 -0.14271953 -1.97020396]
2d Array
[[-1.37585641 -0.72890763  0.55624254  0.13844677]
 [ 0.8271922   0.02514739 -0.76403574  0.56189929]
 [ 0.62362898  2.44720461  0.65128173 -0.45423046]
 [-0.4059621  -0.82196424  0.86941816 -0.8569763 ]]


ranf()

In [13]:
var4=np.random.ranf(5)
print(var4)

[0.46974056 0.76408433 0.20388564 0.61627757 0.8356186 ]


randint()

In [15]:
var5=np.random.randint(3,8,10)
var6=np.random.randint(1,5,(3,3))
print(var5)
print()
print(var6)

[7 4 6 3 4 3 5 4 5 3]

[[3 4 2]
 [3 1 3]
 [1 3 1]]
