# Search

In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,2,56,2])

x=np.where(arr%2==0)
print(x)


(array([1, 3, 5, 6, 7], dtype=int64),)


# search sort

In [16]:
arr=np.array([1,2,3,4,5,7,8,9,10])
x1=np.searchsorted(arr,[6,7,8],side="right")
print(x1)

[5 6 7]


# sort

In [22]:
arr=([3,4,2,5,6,8,1,11,1,65,67,77,2,1])

print(np.sort(arr))

[ 1  1  1  2  2  3  4  5  6  8 11 65 67 77]


In [29]:
arr=np.array(['a','f','b','d'])
print(np.sort(arr))

['a' 'b' 'd' 'f']


In [31]:
arr2=([[5,3,12,32],[56,44,3,1]])
print(np.sort(arr2))

[[ 3  5 12 32]
 [ 1  3 44 56]]


# filter array

In [35]:
arr=np.array(['a','f','b','d'])
f=[True,False,False,True]
arr_new=arr[f]
print(np.sort(arr))
print()
print(arr_new)
print(type(arr_new))

['a' 'b' 'd' 'f']

['a' 'd']
<class 'numpy.ndarray'>
