# shuffle

In [44]:
import numpy as np

arr=np.array([1,2,3,4,5])

np.random.shuffle(arr)

print(arr)

[5 2 3 4 1]


# unique

In [57]:
arr=np.array([9,1,2,1,3,5,2,4,5,5])

x=np.unique(arr,return_index=True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 9]), array([1, 2, 4, 7, 5, 0], dtype=int64), array([2, 2, 1, 1, 3, 1], dtype=int64))


# Resize Flatten Ravel

In [94]:
arr=np.array([1,2,3,4,5,6,7,8])
y=np.resize(arr,(3,3))
print(y)
print()
print(y.flatten(order="F"))
print(y.flatten(order="C"))
print(y.flatten(order="A"))
print(y.flatten(order="K"))
print()

print(np.ravel(y))



[[1 2 3]
 [4 5 6]
 [7 8 1]]

[1 4 7 2 5 8 3 6 1]
[1 2 3 4 5 6 7 8 1]
[1 2 3 4 5 6 7 8 1]
[1 2 3 4 5 6 7 8 1]

[1 2 3 4 5 6 7 8 1]
