Zeros

In [4]:
import numpy as np
ar_zero=np.zeros(4)
ar_zero1=np.zeros((5,5))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Ones Array


In [6]:
ar_ones=np.ones(4)
ar_ones1=np.ones((4,5))
print(ar_ones)
print(ar_ones1)

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Empty

In [8]:
arr_empty=np.empty(5)
print(arr_empty)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.69761995e-312
 0.00000000e+000]


Range

In [24]:
arr_rn=np.arange(5)
print(arr_rn)

[0 1 2 3 4]


Digonal

In [29]:
arr_dia=np.eye(3)
arr_dia1=np.eye(5,5)
print(arr_dia)
print(arr_dia1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


LinSpace

In [35]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
