# split array

In [26]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)
print()
arr_sp=np.array_split(arr,3)
print(arr_sp)

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]


In [30]:
arr=np.array([[1,2,3],[7,8,9],[4,5,6]])
print(arr)
print()
arr_sp=np.array_split(arr,3)
print(arr_sp)

[[1 2 3]
 [7 8 9]
 [4 5 6]]

[array([[1, 2, 3]]), array([[7, 8, 9]]), array([[4, 5, 6]])]
